### ISSUE TITLE
Frog gets progressively slower when running for hours, days

### ISSUE THREAD

**Issue by gmjonker** [LanguageMachines/frog#49] opened 2018-05-14 11:26 UTC
When running frog for a long time, performance decreases significantly. 

For instance, I'm processing a 2.8GB file. These are some `pv` outputs at several moments:

    frog: 15.8MiB  0:05:10 [39.2KiB/s] [>                                 ]  0% ETA  4:20:44:08
    frog:  545MiB  3:29:02 [62.2KiB/s] [>                                 ]  2% ETA  5:13:26:11     
    frog:  858MiB  5:23:19 [30.6KiB/s] [=>                                ]  4% ETA  5:09:10:47
    frog: 3.05GiB 73:28:54 [    0 B/s] [====>                             ] 14% ETA 17:22:57:01

At first, the expected time is 4 days and 20 hours. After having run for 3 days, the expected time has gone up to almost 18 days.

This is the script used:

	#!/usr/bin/env bash
	FILE=$1
	FILE_SIZE=`wc -c < "$FILE" | cut -f1`
	let "EXPECTED_FROG_SIZE = 8 * FILE_SIZE"
	BODY="${FILE%.*}"
	
	echo "Processing: $FILE"
	echo "Size: $FILE_SIZE"
	echo "Writing output to: ${BODY}_frog.txt"
	
	pv -s ${FILE_SIZE} -cN in ${FILE} | frog --skip=acmnp 2> ${BODY}_frog.log | pv -s ${EXPECTED_FROG_SIZE} -cN frog > ${BODY}_frog.txt

**Comment by kosloot** [comment] 2018-05-14 12:49
Well, i am not sure what is happening here, but my first guess is that the process gets low on memory.
Do you have enough RAM to run this kind of large input?
frog will construct a large FoLiA document, covering the whole input. I wouldn't be surprised if it needs 50G of RAM or more.

This is the result of an unfortunate design decision long ago.
For the time being, it might be a solution to split the input file into smaller parts.

You also might experiment with the -n option (one sentence per line) 
or the --threads option, setting it to 1

**Comment by gmjonker** [comment] 2018-05-14 15:44
Frog is currenly using 577MB of memory, see screenshot. 
I will try the `-n` and `--threads=1`.
If it doesn't help, I will split indeed.
![screen shot 2018-05-14 at 17 43 39](https://user-images.githubusercontent.com/6223710/40007962-697d0660-579e-11e8-8234-a2b6fb555033.png)

**Comment by kosloot** [comment] 2018-05-14 17:43
Hmm, this is strange.
it might be that Frog is deadlocking on the threads.
is it producing any output? 
if you have the rights, you could try 'strace -p 25773'
if the only thing it shows is a futex-wait then your are probably lost.

Side note:
Is this problem reproducible? Or just once in a while?

Is all else fails, is it possible to give me the offensive file?

**Comment by gmjonker** [comment] 2018-05-15 07:46
Frog is still producing output, but just very slowly. 
The behaviour is always the same.
I should also mention that I'm running frog in `proycon/lamachine`
I'm now testing with `--threads=1`

**Comment by kosloot** [comment] 2018-05-15 09:05
hmm. OK. getting out of clues then....
Is the 2.5 Gb available for me? for analyzing.

**Comment by gmjonker** [comment] 2018-05-18 14:53
`--threads=1` doesn't help.

**Comment by kosloot** [comment] 2018-05-25 15:49
still puzzling...
Somehow its seems that programs get slower with increasing size of the OUTPUT files.
Checked this with 'mblem' too.
First thought: 'pv' get in the way. But also without pv is slows down.
Next guess: using cout and redirecting slows it down.
So I added an output parameter to mblem, to write directly to a file.
But to no avail... at least, nor really.
But for output files < 1.5 Gb it seems reasonable. So splitting seems the way to go.
Bit still....
This is nerve-wrecking....

**Comment by asharkinasuit** [comment] 2018-10-08 07:00
An update perhaps: I've been running frog 0.15 (based on ucto 0.13.2, libfolia 1.13, timbl 6.4.12, ticcutils 0.19, mbt 3.3.2) for the past several days on the COW corpus. I knew there was no way that was all fitting in memory, so I split it into files of 10k sentences each and asked frog to run on them using `frog --testdir=. -n --skip=cmnp --xmldir=. --nostdout` (just to be complete; the point is probably the -n --threads stuff, but I can say I only need the lemmas and didn't want to slow things down with a parse.)
I let it run over the weekend and it looks like it processed about 80 files on Friday, 70 on Saturday and 40 on Sunday. The new clue to the problem I would contribute is that it started with 8 threads, but this morning I found it using only one thread (by CPU usage anyway). Memory is not a problem on the machine I'm using, but maybe the threads are dying or getting killed for some reason? Not sure this relates to the above problems, since there apparently threads don't help, but maybe this is still worth looking into.

PS Sorry I didn't check to see if threads died or just CPU use reduced; I can let it run this week and check when it slows down again.

**Comment by kosloot** [comment] 2018-10-08 07:33
Hi,
thanks for the update.
to start of: I am surprised about the numbers files you mention. We are used to processing 1000 files per hour or so. So probably your files are very, very large?

The idea of thread starving might be interesting to look at, but:
drum-roll...
I am working on a re-implementation of Frog, aiming at speed, memory footprint and less locking.
So fixing the current Frog is not a high priority.
The work is going well, but slow. A first release is scheduled a month (or two...) form now.

Feel free to checkout the ``new_datastructure`` branch of frog and test it. 
You will also need the ``foliareader`` branch for libfolia then.
NO WARRANTY

**Comment by kosloot** [comment] 2020-03-26 15:32
Well, the new implementation is around for quite a while now. Don't know if it made any difference.
But at the moment work on Frog is on a hold. except for real bugs.
If work will ever be picked up is dependent on real demand, accompanied by some currency.
So closing this issue for now.

**Closed by kosloot** 2020-03-26 15:32 UTC
Labels: help wanted
