### ISSUE TITLE
Frog / lamachine server waits 20 seconds before starting processing 

### ISSUE THREAD

**Issue by vanatteveldt** [LanguageMachines/frog#65] opened 2019-02-22 13:39 UTC
When I run frog via lamachine docker it only starts processing after 20 seconds. I think this is new since I didn't run into this problem earlier. 

Steps to reproduce:

1) get  latest lamachine running and serving frog:

```{sh}
$ docker pull proycon/lamachine:latest
$ docker run --name lamachine -dp 9887:9887 proycon/lamachine frog -S 9887 --skip=pm
```
2) Setup client

```{sh}
$ python3 -m venv frogenv
$ frogenv/bin/pip install pynlpl
[..]
$ echo "from pynlpl.clients.frogclient import FrogClient
> frogclient = FrogClient('localhost', 9887)
> print(list(frogclient.process('Een voorbeeldbericht om te froggen')))
> " > test.py
```

3) Send sentence to server:

```{sh}
$ date; time frogenv/bin/python test.py
vr 22 feb 2019 14:33:22 CET
[('Een', 'een', '[een]', 'LID(onbep,stan,agr)'), ('voorbeeldbericht', 'voorbeeldbericht', '[voor][beeld][bericht]', 'N(soort,ev,basis,zijd,stan)'), ('om', 'om', '[om]', 'VZ(init)'), ('te', 'te', '[te]', 'VZ(init)'), ('froggen', 'froggen', '[froggen]', 'WW(inf,vrij,zonder)')]

real	0m20,407s
user	0m0,031s
sys	0m0,009s
```

As you can see, it took int total command 20 seconds to run the command. Docker logs:

```{sh}
$ docker logs -f lamachine
frog 0.15 (c) CLTS, ILK 1998 - 2018
CLST  - Centre for Language and Speech Technology,Radboud University
ILK   - Induction of Linguistic Knowledge Research Group,Tilburg University
based on [ucto 0.14.1, libfolia 1.15, timbl 6.4.13, ticcutils 0.20, mbt 3.4]
[..]
frog-:Fri Feb 22 13:31:45 2019 Initialization done.
[..]
frog-:New connection...
frog-:Fri Feb 22 13:33:42 2019 Processing... 
[..]
```

Looking at the logs while waiting nothing happened until the 20 seconds passed. Comparing the time stamps you can see there's a 20 second delay between the 'date' command and the 'new connection / processing' log message.

[edit: added frog version in log]

**Comment by nruigrok** [comment] 2019-02-23 20:45
Note: on a machine with an existing (older?)  install of the docker image the problem does not occur, so it might be a recent change that causes the problem?

```
$ sudo docker logs kickass_hoover 2>&1 | head
frog 0.13.3 (c) CLTS, ILK 1998 - 2016
~$ time frogenv/bin/python test.py
[('Een', 'een', '[een]', 'LID(onbep,stan,agr)'), ('voorbeeldbericht', 'voorbeeldbericht', '[voor][beeld][bericht]', 'N(soort,ev,basis,zijd,stan)'), ('om', 'om', '[om]', 'VZ(init)'), ('te', 'te', '[te]', 'VZ(init)'), ('froggen', 'froggen', '[froggen]', 'WW(inf,vrij,zonder)')]

real	0m0,296s
user	0m0,022s
sys	0m0,004s
```

**Comment by proycon** [comment] 2019-02-25 15:09
This looks weird indeed, things should be pretty fast once the initial startup is complete.
Hold on for a bit, we'll have to see if we can reproduce this.

**Comment by proycon** [comment] 2019-02-26 09:09
I tried to replicate your set up with LaMachine docker exactly, thanks to your detailed instructions, but the problem does not reproduce here:

```
Tue 26 Feb 09:36:42 CET 2019
[('Een', 'een', '[een]', 'LID(onbep,stan,agr)'), ('voorbeeldbericht', 'voorbeeldbericht', '[voor][beeld][bericht]', 'N(soort,ev,basis,zijd,stan)'), ('om', 'om', '[om]', 'VZ(init)'), ('te', 'te', '[te]', 'VZ(init)'), ('froggen', 'froggen', '[froggen]', 'WW(inf,vrij,zonder)')]
python test.py  0.03s user 0.00s system 10% cpu 0.306 total
```

```
frog 0.15 (c) CLTS, ILK 1998 - 2018
CLST  - Centre for Language and Speech Technology,Radboud University
ILK   - Induction of Linguistic Knowledge Research Group,Tilburg University
based on [ucto 0.14.1, libfolia 1.15, timbl 6.4.13, ticcutils 0.20, mbt 3.4]
```

So I'm still in the dark what is the cause could be in your case.

**Comment by proycon** [comment] 2019-02-26 09:17
Perhaps you could try telnetting to the frog server port to determine whether the delay is server-side or (as I suspect) client-side. Or if the socket is delayed in responding somehow?

**Comment by kosloot** [comment] 2020-03-26 15:04
closing this due to lack of information

**Closed by kosloot** 2020-03-26 15:04 UTC
